=== drnikolaev/runge/runge/Runge/RungeConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:runge="http://www.cvmlib.com/runge" targetNamespace="http://www.cvmlib.com/runge" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="solvers">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="solver" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="dll" type="xs:string"/>
										<xs:element name="routine" type="xs:string"/>
										<xs:element name="size2" type="xs:unsignedByte"/>
										<xs:element name="size1" type="xs:unsignedByte"/>
										<xs:element name="size0" type="xs:unsignedByte"/>
										<xs:element name="name" type="xs:string"/>
									</xs:sequence>
									<xs:attribute name="type" type="runge:SolverType" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="SolverType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FTX_F"/>
			<xs:enumeration value="AFI_FAFI"/>
			<xs:enumeration value="FTX_FFJ"/>
			<xs:enumeration value="BUTX_BFU"/>
			<xs:enumeration value="FX_FFJ"/>
			<xs:enumeration value="FTX_FFJFT"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== drnikolaev/runge/runge/Runge/RungeLinux64.xml
<?xml version="1.0" encoding="utf-8"?>
<runge:config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:runge="http://www.cvmlib.com/runge" xsi:schemaLocation="http://www.cvmlib.com/runge RungeConfig.xsd" >
  <solvers>

    <solver type="FTX_F">
      <dll>../../../lib64/libdes_engl_em64t_ilp64_debug.so</dll>
      <routine>sengl_</routine>
      <size2>0</size2>
      <size1>7</size1>
      <size0>0</size0>
      <name>England: x' = F(t,x)</name>
    </solver>

    <solver type="AFI_FAFI">
      <dll>../../../lib64/libdes_lou_em64t_ilp64_debug.so</dll>
      <routine>sloui_</routine>
      <size2>7</size2>
      <size1>5</size1>
      <size0>0</size0>
      <name>Lawson: x' = A(t)x + fi(t)</name>
    </solver>

    <solver type="FTX_FFJ">
      <dll>../../../lib64/libdes_lou_em64t_ilp64_debug.so</dll>
      <routine>sloun_</routine>
      <size2>6</size2>
      <size1>6</size1>
      <size0>0</size0>
      <name>Lawson: x' = F(t,x)</name>
    </solver>

    <solver type="BUTX_BFU">
      <dll>../../../lib64/libdes_lou_em64t_ilp64_debug.so</dll>
      <routine>slouu_</routine>
      <size2>5</size2>
      <size1>6</size1>
      <size0>0</size0>
      <name>Lawson: x' = Bx + f(t,x)</name>
    </solver>

    <solver type="FX_FFJ">
      <dll>../../../lib64/libdes_ros_em64t_ilp64_debug.so</dll>
      <routine>srosa_</routine>
      <size2>6</size2>
      <size1>4</size1>
      <size0>0</size0>
      <name>Rosenbrock: x' = F(x)</name>
    </solver>

    <solver type="FTX_FFJFT">
      <dll>../../../lib64/libdes_ros_em64t_ilp64_debug.so</dll>
      <routine>srosn_</routine>
      <size2>6</size2>
      <size1>6</size1>
      <size0>0</size0>
      <name>Rosenbrock: x' = F(t,x)</name>
    </solver>

  </solvers>
</runge:config>

=== drnikolaev/runge/runge/Runge/RungeLinux.xml
<?xml version="1.0" encoding="utf-8"?>
<runge:config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:runge="http://www.cvmlib.com/runge" xsi:schemaLocation="http://www.cvmlib.com/runge RungeConfig.xsd" >
  <solvers>

    <solver type="FTX_F">
      <dll>../../../lib/libdes_engl_ia32.so</dll>
      <routine>sengl_</routine>
      <size2>0</size2>
      <size1>7</size1>
      <size0>0</size0>
      <name>England: x' = F(t,x)</name>
    </solver>

    <solver type="AFI_FAFI">
      <dll>../../../lib/libdes_lou_ia32.so</dll>
      <routine>sloui_</routine>
      <size2>7</size2>
      <size1>5</size1>
      <size0>0</size0>
      <name>Lawson: x' = A(t)x + fi(t)</name>
    </solver>

    <solver type="FTX_FFJ">
      <dll>../../../lib/libdes_lou_ia32.so</dll>
      <routine>sloun_</routine>
      <size2>6</size2>
      <size1>6</size1>
      <size0>0</size0>
      <name>Lawson: x' = F(t,x)</name>
    </solver>

    <solver type="BUTX_BFU">
      <dll>../../../lib/libdes_lou_ia32.so</dll>
      <routine>slouu_</routine>
      <size2>5</size2>
      <size1>6</size1>
      <size0>0</size0>
      <name>Lawson: x' = Bx + f(t,x)</name>
    </solver>

    <solver type="FX_FFJ">
      <dll>../../../lib/libdes_ros_ia32.so</dll>
      <routine>srosa_</routine>
      <size2>6</size2>
      <size1>4</size1>
      <size0>0</size0>
      <name>Rosenbrock: x' = F(x)</name>
    </solver>

    <solver type="FTX_FFJFT">
      <dll>../../../lib/libdes_ros_ia32.so</dll>
      <routine>srosn_</routine>
      <size2>6</size2>
      <size1>6</size1>
      <size0>0</size0>
      <name>Rosenbrock: x' = F(t,x)</name>
    </solver>

  </solvers>
</runge:config>

=== drnikolaev/runge/runge/Runge/Runge64.xml
<?xml version="1.0" encoding="utf-8"?>
<runge:config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:runge="http://www.cvmlib.com/runge" xsi:schemaLocation="http://www.cvmlib.com/runge RungeConfig.xsd" >
  <solvers>

    <solver type="FTX_F">
      <dll>../../../../lib64/des_engl_em64t_ilp64.dll</dll>
      <routine>SENGL</routine>
      <size2>0</size2>
      <size1>7</size1>
      <size0>0</size0>
      <name>England: x' = F(t,x)</name>
    </solver>

    <solver type="AFI_FAFI">
      <dll>../../../../lib64/des_lou_em64t_ilp64.dll</dll>
      <routine>SLOUI</routine>
      <size2>7</size2>
      <size1>5</size1>
      <size0>0</size0>
      <name>Lawson: x' = A(t)x + fi(t)</name>
    </solver>

    <solver type="FTX_FFJ">
      <dll>../../../../lib64/des_lou_em64t_ilp64.dll</dll>
      <routine>SLOUN</routine>
      <size2>6</size2>
      <size1>6</size1>
      <size0>0</size0>
      <name>Lawson: x' = F(t,x)</name>
    </solver>

    <solver type="BUTX_BFU">
      <dll>../../../../lib64/des_lou_em64t_ilp64.dll</dll>
      <routine>SLOUU</routine>
      <size2>5</size2>
      <size1>6</size1>
      <size0>0</size0>
      <name>Lawson: x' = Bx + f(t,x)</name>
    </solver>

    <solver type="FX_FFJ">
      <dll>../../../../lib64/des_ros_em64t_ilp64.dll</dll>
      <routine>SROSA</routine>
      <size2>6</size2>
      <size1>4</size1>
      <size0>0</size0>
      <name>Rosenbrock: x' = F(x)</name>
    </solver>

    <solver type="FTX_FFJFT">
      <dll>../../../../lib64/des_ros_em64t_ilp64.dll</dll>
      <routine>SROSN</routine>
      <size2>6</size2>
      <size1>6</size1>
      <size0>0</size0>
      <name>Rosenbrock: x' = F(t,x)</name>
    </solver>

  </solvers>
</runge:config>
